User.destroy_all
User.create!(
  [{
    "id": 1,
    "name": "Nicole",
    "email": "npuckring0@umich.edu",
    "password": "ZcNLpVSGfK9"
  }, {
    "id": 2,
    "name": "Mikol",
    "email": "mhardage1@discuz.net",
    "password": "YSTbX2EbPAz"
  }, {
    "id": 3,
    "name": "Bertrando",
    "email": "bsciusscietto2@tinypic.com",
    "password": "7q7XH0JEB"
  }, {
    "id": 4,
    "name": "Myrlene",
    "email": "mkolin3@va.gov",
    "password": "9ZSlChA"
  }, {
    "id": 5,
    "name": "Lurleen",
    "email": "lharse4@xinhuanet.com",
    "password": "uDeEGCRYYl4"
  }, {
    "id": 6,
    "name": "Ewart",
    "email": "edacres5@hexun.com",
    "password": "EWt8D2eVjPMg"
  }, {
    "id": 7,
    "name": "Lilia",
    "email": "ldefilippo6@usnews.com",
    "password": "gjsPJqDgP"
  }, {
    "id": 8,
    "name": "Kimble",
    "email": "kseeking7@networkadvertising.org",
    "password": "WAT8mhUxWitC"
  }, {
    "id": 9,
    "name": "Kayne",
    "email": "ktuddenham8@home.pl",
    "password": "KAbxq0ADp6"
  }, {
    "id": 10,
    "name": "Baily",
    "email": "bhebborne9@stanford.edu",
    "password": "9TgCV0"
  }, {
    "id": 11,
    "name": "Kimberly",
    "email": "klowbridgea@t.co",
    "password": "13QRyC"
  }, {
    "id": 12,
    "name": "Mitch",
    "email": "mdevenishb@eventbrite.com",
    "password": "cqCzrMX"
  }, {
    "id": 13,
    "name": "Dianne",
    "email": "dzaczekc@desdev.cn",
    "password": "EbkeWA4fF"
  }, {
    "id": 14,
    "name": "Borg",
    "email": "bgoodlifed@redcross.org",
    "password": "1qwz3W87"
  }, {
    "id": 15,
    "name": "Gwendolyn",
    "email": "gchsteneye@google.com",
    "password": "lxXKO90NbeM"
  }, {
    "id": 16,
    "name": "Montgomery",
    "email": "mtonksf@zdnet.com",
    "password": "MStwBdRT"
  }, {
    "id": 17,
    "name": "Kellby",
    "email": "kbassingdeng@unc.edu",
    "password": "seo7UWMemq"
  }, {
    "id": 18,
    "name": "Elizabet",
    "email": "estodeh@craigslist.org",
    "password": "9Xi7mFGmQD"
  }, {
    "id": 19,
    "name": "Raven",
    "email": "raneleyi@bluehost.com",
    "password": "nRkgJdE"
  }, {
    "id": 20,
    "name": "Pierre",
    "email": "pstatefieldj@fc2.com",
    "password": "IRpljLTzv"
  }, {
    "id": 21,
    "name": "Clem",
    "email": "cbackshillk@hc360.com",
    "password": "Q2chMlcX2"
  }, {
    "id": 22,
    "name": "Elwyn",
    "email": "efeorel@loc.gov",
    "password": "9uGqmT"
  }, {
    "id": 23,
    "name": "Courtney",
    "email": "cmcbeithm@miibeian.gov.cn",
    "password": "xOhni8483"
  }, {
    "id": 24,
    "name": "Averill",
    "email": "aswindleyn@deviantart.com",
    "password": "cemJTjrzI"
  }, {
    "id": 25,
    "name": "Suzy",
    "email": "skorneichuko@nps.gov",
    "password": "2624RH3L8K"
  }])
